version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "16:00"
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: "gomod"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "16:00"
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: "all"
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: "gomod"
    directory: "/.examples/serverless/aws_lambda"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "16:00"
  - package-ecosystem: "gomod"
    directory: "/.examples/serverless/azure_functions"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "16:00"
  - package-ecosystem: "gomod"
    directory: "/.examples/serverless/digitalocean_functions/packages/email-sender/send-email"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "16:00"
  - package-ecosystem: "gomod"
    directory: "/.examples/serverless/google_cloud_functions"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "16:00"