name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: 'Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: 'Refactoring'
    labels:
      - 'refactor'
      - 'refactoring'
  - title: 'Documentation'
    labels:
      - 'docs'
      - 'documentation'
  - title: 'Features'
    labels:
      - 'feat'
      - 'feature'
      - 'enhancement'
  - title: 'Maintenance'
    labels:
      - 'chore'
      - 'maintenance'
    collapse-after: 5

autolabeler:
  - label: 'docs'
    files:
      - '*.md'
    branch:
      - /docs\/.+/'
    title:
      - '/docs/\(/i'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
      - '/Hotfix\/.+/'
    title:
      - '/fix/\(/i'
  - label: 'enhancement'
    branch:
      - '/feature\/.+/'
    title:
      - '/feature/\(/i'
      - '/feat/\(/i'
  - label: 'chore'
    branch:
      - '/chore\/.+/'
    title:
      - '/chore/\(/i'
  - label: 'refactor'
    branch:
      - '/refactor\/.+/'
    title:
      - '/refactor/\(/i'

      

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch


template: |
  ## Description

  This release marks the full release of version v$RESOLVED_VERSION with significant improvements and additions. Key changes include bug fixes, refactoring, updated documentation, new features, and maintenance updates.
  
  ## What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
