packages:
  - name: email-sender
    environment:
        SMTP_HOST: "${SMTP_HOST}"
        SMTP_PORT: "${SMTP_PORT}"
        SMTP_USER: "${SMTP_PASSWORD}"
        SMTP_PASSWORD: "${SMTP_PASSWORD}"
        SMTP_AUTH_METHOD: "${SMTP_AUTH_METHOD}"
    actions:
      - name: send-email
        runtime: 'go:1.20'