name: FOSSA Compliance Check

permissions:
  contents: read

on:
  push:
    branches:
      - main
      - develop

jobs:
  fossa-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - uses: fossas/fossa-action@09bcf127dc0ccb4b5a023f6f906728878e8610ba # v1.4.0
        with:
          api-key: ${{secrets.fossaApiKey}}
