name: GoVulnCheck

permissions:
  contents: read

on: [push]


jobs:
  govulncheck_job:
    runs-on: ubuntu-latest
    name: Run govulncheck
    steps:
      - id: govulncheck
        uses: golang/govulncheck-action@b625fbe08f3bccbe446d94fbf87fcc875a4f50ee # v1.0.4
        with:
           go-version-input: 1.22.5
           go-package: ./...
